stages:
  - prepare
  - test
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

prepare_frontend:
  stage: prepare
  script:
    - pwd
    - nix develop -c bash -c "make pre-front"
  artifacts:
    paths:
      - client/node_modules

prepare_backend:
  stage: prepare
  script:
    - nix develop -c bash -c "make pre-back"
  artifacts:
    paths:
      - server/.stack-work

test_frontend:
  stage: test
  dependencies:
    - prepare_frontend
  script:
    - nix develop -c bash -c "make test-front"

test_backend:
  stage: test
  dependencies:
    - prepare_backend
  script:
    - nix develop -c bash -c "make test-back"

build_backend:
  stage: build
  dependencies:
    - prepare_backend
  script:
    - echo "build backend"
  artifacts:
    paths:
      - server/.stack-work
