stages:
  - test
  - build
  - deploy

variables:
  YESOD_PGUSER: $YESOD_PGUSER
  YESOD_PGPASS: $YESOD_PGPASS
  YESOD_PGHOST: $YESOD_PGHOST
  YESOD_PGPORT: $YESOD_PGPORT
  YESOD_PGPORT_TEST: $YESOD_PGPORT_TEST
  YESOD_PGDATABASE: $YESOD_PGDATABASE
  YESOD_PGDATABASE_TEST: $YESOD_PGDATABASE_TEST
  SECRET: $SECRET
  SALT: $SALT

test_frontend:
  stage: test
  script:
    - nix develop -c bash -c "make pre-front"
    - nix develop -c bash -c "make ci-test-unit-front"
  artifacts:
    paths:
      - client/node_modules

test_backend:
  stage: test
  script:
    - docker compose -f ./server/docker-compose.yml up -d db-test
    - YESOD_PGHOST=localhost nix develop -c bash -c "make ci-test-back"
  artifacts:
    paths:
      - server/.stack-work

build_frontend:
  stage: build
  dependencies:
    - test_frontend
  script:
    - nix develop -c bash -c "make ci-build-front"
  artifacts:
    paths:
      - client/dist

deploy_backend:
  stage: deploy
  dependencies:
    - test_backend
  script:
    - nix develop -c bash -c "make ci-deploy-back"
    
deploy_frontend:
  stage: deploy
  dependencies:
    - build_frontend
  script:
    - nix develop -c bash -c "make ci-deploy-front"
