stages:
  - prepare
  - test
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  # Check if Nix is already installed
  - |
    if ! command -v nix &> /dev/null; then
      echo "Nix is not installed. Installing Nix..."
      mkdir -m 0755 /nix && chown $USER /nix
      curl -L https://nixos.org/nix/install | sh
      . /home/$USER/.nix-profile/etc/profile.d/nix.sh
    else
      echo "Nix is already installed."
      . /home/$USER/.nix-profile/etc/profile.d/nix.sh
    fi

prepare_frontend:
  stage: prepare
  script:
    - nix develop -c bash -c "make pre-front"
  artifacts:
    paths:
      - client/node_modules

prepare_backend:
  stage: prepare
  script:
    - echo "prepare backend"
  artifacts:
    paths:
      - server/.stack-work

test_frontend:
  stage: test
  dependencies:
    - prepare_frontend
  script:
    - nix develop -c bash -c "make test-front"

test_backend:
  stage: test
  dependencies:
    - prepare_backend
  script:
    - echo "test backend"

build_backend:
  stage: build
  dependencies:
    - prepare_backend
  script:
    - ecoh "build backend"
  artifacts:
    paths:
      - server/.stack-work
