services:
  db:
    image: postgres:15.7
    container_name: db
    environment:
      POSTGRES_USER: ${YESOD_PGUSER}
      POSTGRES_PASSWORD: ${YESOD_PGPASS}
      POSTGRES_DB: ${YESOD_PGDATABASE}
    ports:
      - "${YESOD_PGPORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    driver: local
